site_name: Polygraph
site_url: https://victor99pekk.github.io/polygraph/
repo_url: https://github.com/victor99pekk/polygraph
theme:
  name: material

nav:
  - Home: docs/index.md
  - Tutorial: docs/tutorial.md
  - API Reference: docs/api_reference.md
  - Data Format: docs/input_data_format.md
  - Contributing: CONTRIBUTING.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
